- name: install apt-cacher-ng
  package: name=apt-cacher-ng state=present


# `lineinfile` is a hack.
# But, we just want to disable a couple features.
# Avoid writing the whole file for now.

# ... of course this has the problem of not taking effect
# before apt-cacher-ng has already been started... 
# "The management web interface which allows execution of certain operations
#  can be protected by HTTP credentials" except no-one knows how.
# Anyway, I just don't want it.
#
- name: Disable control page
  lineinfile:
    dest: /etc/apt-cacher-ng/acng.conf
    regexp: '^(#?)ReportPage:'
    line: '#ReportPage: # non-essential, disabled for security'
  notify: [ 'Restart apt-cacher-ng' ]

- name: Disable web server (localhost:3142/acng-doc)
  lineinfile:
    dest: /etc/apt-cacher-ng/acng.conf
    regexp: '^(#?)LocalDirs:'
    line: '#LocalDirs: # not required, disabled as security precaution'
  notify: [ 'Restart apt-cacher-ng' ]


# backends_ configuration files
#
- name: Set Debian repo to primary UK mirror
  copy:
    content: |
      http://ftp.uk.debian.org/debian/
    dest: /etc/apt-cacher-ng/backends_debian
  notify: [ 'Restart apt-cacher-ng' ]

- name: Set Ubuntu repo to UK mirrorservice.org
  copy:
    content: |
      http://www.mirrorservice.org/sites/archive.ubuntu.com/ubuntu/
    dest: /etc/apt-cacher-ng/backends_ubuntu
  notify: [ 'Restart apt-cacher-ng' ]


- name: ensure apt-cacher-ng is enabled
  service:
    name: apt-cacher-ng
    enabled: yes
    state: started

