- name: Check OS is Debian
  assert:
    that: "ansible_distribution == 'Debian'"

- name: Configure apt to use local caching proxy
  copy:
    src: apt.conf.d/02proxy
    dest: /etc/apt/apt.conf.d/
  register: proxy

- name: Configure apt to use UK mirror
  copy:
    src: '{{ repos_debian__dist }}-sources.list'
    dest: /etc/apt/sources.list
  register: sources

# This test is slow, only bother when changed.
# (In which case, the next use of apt-get would probably have had to do this anyway).
- name: Test "apt-get update"
  when: proxy.changed or sources.changed
  command: apt-get update
  register: update
  failed_when: |
    "\nErr " in ("\n" + update.stdout) or
    "\nW: "  in ("\n" + update.stderr)
  args:
    warn: no  # don't use apt module, it has to update cache in check mode
