# X201 is retired from being primary workstation
# due to failing hardware
#
- hosts: alan-x201
  roles:
    - repos-fedora
    - etckeeper

    - openssh-server
    - ssh-authkeys

    # Thinkpad X201 seems perfectly happy with `powertop --auto-tune`.
    - powertop-full-override

    - packages-gui
    - sourcejedi.google-chrome

    - packages-dev-basics
    - sourcejedi.rpmfusion-free  # e.g. `lame`
