- hosts: drystone
  roles:
    - role: repos-apt
      repos_apt: debian-jessie
    - repos-debian-jessie-backports

    - sourcejedi.etckeeper

    # Note - remote administration is not permitted.
    # We run ssh server but use AllowGroups.
    - openssh-server

    #- packages-gui  # says firefox, but debian package is firefox-esr
    - sourcejedi.google-chrome
