# Small nspawn for service which I need newer version

- hosts: unstable
  roles:
    - repos-debian-unstable
    - sourcejedi.etckeeper

    - debian-unattended-upgrades

    - apt-cacher-ng

  tasks:
