- hosts: test-vm-debian
  roles:
    - repos-apt
    - role: repos-debian-jessie-backports
      when: repos_apt == 'debian-jessie'

    - sourcejedi.etckeeper

    - users
    - openssh-server

    - packages-dev-basics
    - sourcejedi.google-chrome
