- name: Install unattended-upgrades
  package: name=unattended-upgrades state=present

- name: Configure unattended-upgrades
  copy:
    src: apt.conf.d
    dest: /etc/apt

- name: Install needrestart
  package: name=needrestart state=present

- name: Configure needrestart
  copy:
    src: needrestart.conf
    dest: /etc/needrestart/
